import localFont from 'next/font/local';
import './globals.css';
import { Inter, Oswald, Playfair_Display } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const oswald = Oswald({ subsets: ['latin'] });
const playfair = Playfair_Display({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${oswald.variable} ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
